[SUPABASE]
URL = "https://hhpkaizvxrhjqjfbyxji.supabase.co"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocGthaXp2eHJoanFqZmJ5eGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQxMzM4MjgsImV4cCI6MjAyOTcwOTgyOH0.f6jYau2PWoMbfbMZ3ijoEooW75lwC-S-ZK6hrTAJprg"